const codes = [
  'WESTPHALIA-1648','WALKER-7759','LATOUR-NETWORK','ARENDT-AUTHORITY','KRASNER-HYPOCRISY','GOD-IS-DEAD','MATERIAL-SYMBOLIC','ORGANIZING-BODY','UNSCOP-1947','SMALLPOX-1979','META-SOVEREIGN','BALFOUR-1917','BOURDIEU-HABITUS','FOUCAULT-TRUTH','COX-PURPOSE'
];
const cases = {
  pakistan:{title:'Pakistan',score:64,tags:['material constraint','symbolic fracture','not zero-sum','IMF dependency'],summary:'Pakistan has formal sovereignty: UN seat, territory, nuclear capacity, bureaucracy. Winston reads the deeper problem: material reproduction is externally constrained by debt and IMF dependence while symbolic reproduction is fractured across military-civilian authority, language, and generational identity.',material:['FX reserves and debt servicing','IMF conditionality','fiscal space','infrastructure and energy vulnerability'],symbolic:['civilian vs military legitimacy','Urdu / English / regional language fracture','national identity reproduction','recognition of state authority'],verdict:'Genuine sovereign capacity, but with diminishing autonomy over the conditions of reproduction.'},
  ukraine:{title:'Ukraine / Russia',score:81,tags:['zero-sum symbolic contest','heritage targeting','memory infrastructure'],summary:'The Westphalian model sees territorial invasion. Winston also sees the systematic attack on Ukraine’s symbolic conditions of reproduction: heritage sites, archives, language, memory, and the ability to recognize itself as continuous over time.',material:['territory','infrastructure','energy grid','military survival'],symbolic:['heritage destruction','archives and memory','language and identity','continuity of peoplehood'],verdict:'Zero-sum on symbolic terms. A ceasefire line alone cannot restore the symbolic conditions of reproduction.'},
  palestine:{title:'Palestine / UNSCOP',score:90,tags:['existential claim','Balfour','UNSCOP','institutional management'],summary:'The Balfour Declaration and UNSCOP proceedings show sovereignty as a hierarchy of recognition. One group’s collective claim was framed politically; another’s was reduced to civil and religious rights. Winston treats this as a structural sovereignty conflict.',material:['land','refugee infrastructure','government machinery','movement and livelihood'],symbolic:['political recognition','national culture','historical continuity','legal standing'],verdict:'Structurally irresolvable through the Westphalian framework. The UN can manage expression, but cannot dissolve the underlying claim conflict.'},
  myanmar:{title:'Myanmar / Meta',score:77,tags:['platform sovereignty','identity erasure','algorithmic governance'],summary:'Meta is not sovereign in the Westphalian sense. Winston asks a different question: did Meta discipline symbolic conditions at scale? In Myanmar, platform amplification shaped the environment in which one community’s identity was dehumanized and made vulnerable to destruction.',material:['platform infrastructure','data flows','ranking systems','communication access'],symbolic:['dehumanizing narratives','religious identity data','visibility and erasure','community representation'],verdict:'A non-state organizing body can exercise sovereign capacity without recognizing itself as sovereign.'},
  isis:{title:'ISIS',score:73,tags:['non-state sovereignty','taxation','myth and governance'],summary:'ISIS exercised core sovereign capacities without formal state recognition: taxation, governance, violence, population control, and a symbolic identity capable of organizing loyalty beyond territory.',material:['taxation systems','territorial control','trade routes','administrative bodies'],symbolic:['caliphate myth','membership identity','religious-political authority','propaganda infrastructure'],verdict:'Territorial defeat destroyed much of the material claim, but symbolic infrastructure can persist in fragmented forms.'},
  smallpox:{title:'Smallpox eradication',score:24,tags:['shared sovereignty','WHO','cooperation','not zero-sum'],summary:'Smallpox shows the other side of the framework. Biological survival was genuinely shared. Even the United States and Soviet Union cooperated during the Cold War because no state could secure itself independently from transnational disease.',material:['vaccines','surveillance','public health logistics','international personnel'],symbolic:['trust in WHO coordination','scientific legitimacy','shared vulnerability','collective survival'],verdict:'Shared sovereignty. Institutional resources should go toward coordination, not zero-sum bargaining.'}
};
const sources = [
 ['Arendt','Authority as relational legitimacy, distinct from coercion and persuasion.'],['Bourdieu','Habitus and fields explain why sovereign authority appears natural while being continuously reproduced.'],['Latour','Actor-network theory: actors are constituted through networks, not prior to them.'],['Foucault','Regimes of truth decide which claims become real, legitimate, and repeatable.'],['Krasner','Organized hypocrisy exposes the gap between sovereignty rules and sovereignty practice.'],['Walker','Inside/outside distinction explains belonging, exclusion, and the violence sovereignty enables.'],['Cox','Theory is always for someone and for some purpose; Winston makes that purpose explicit.'],['Lévi-Strauss','Myth organizes meaning rather than merely describing empirical truth.'],['Swidler','Culture as toolkit: myths and symbols are used strategically to reproduce identity.'],['Flemming','State responsibility and algorithmic/non-human decision systems.'],['UN Charter / Moscow Conference','Institutionalization of sovereign equality in the post-war order.'],['UNSCOP 1947','Sovereignty expressed as existential material and symbolic necessity.'],['Balfour Declaration','Political recognition for one claim, civil/religious reduction for another.'],['WHO / Smallpox','Shared sovereignty and global cooperation under biological interdependence.'],['Meta / Haugen / Myanmar','Platform governance, data flows, and symbolic conditions at scale.'],['IMF / Pakistan','Material sovereignty, recurring external constraint, and formal-state fragility.'],['Kallman / Ukraine heritage','Symbolic destruction as strategy against identity reproduction.'],['Orwell 1984','Narrative control, memory, and the institutional rewriting of reality.']
];
const answers = {
 'definition':'Sovereignty is not a thing the state simply has. In this framework it is a continuous system: an organizing body claims, in relation to another, the dynamic capacity to discipline and control the material and symbolic conditions necessary for its own reproduction over time.',
 'pakistan':'Pakistan has the formal signs of Westphalian sovereignty, but Winston separates form from reproduction. The material layer is constrained by debt, FX reserves, IMF dependency, and fiscal limits. The symbolic layer is fractured across military-civilian legitimacy, language politics, and generational identity. The result is sovereign capacity with reduced autonomy over the terms of reproduction.',
 'meta':'Meta matters because the Westphalian model has no good category for it. It governs digital infrastructure, information circulation, identity representation, and political visibility for billions of people. That does not make it a state; it makes it an organizing body capable of disciplining symbolic conditions at scale.',
 'ukraine':'Ukraine reveals that territorial invasion is only one layer of sovereign destruction. The symbolic layer includes heritage, archives, language, memory, and the conditions through which a people recognizes itself as continuous. Winston treats attacks on that layer as sovereign strategy, not collateral damage.'
};
let activeCode = codes[Math.floor(Math.random()*codes.length)];
document.getElementById('generatedCode').textContent = activeCode;
document.body.classList.add('locked');
function tickClocks(){
 const opts={hour:'2-digit',minute:'2-digit',hour12:false};
 const set=(id,tz)=>document.getElementById(id).textContent=new Intl.DateTimeFormat('en-US',{...opts,timeZone:tz}).format(new Date());
 set('clockNY','America/New_York');set('clockGE','Europe/Zurich');set('clockIS','Asia/Karachi');set('clockDE','Asia/Kolkata');
}
tickClocks(); setInterval(tickClocks,1000);
document.addEventListener('mousemove',e=>{const x=e.clientX/window.innerWidth-.5,y=e.clientY/window.innerHeight-.5;document.documentElement.style.setProperty('--mx',x);document.documentElement.style.setProperty('--my',y);document.querySelector('.cursor-orb').style.left=e.clientX+'px';document.querySelector('.cursor-orb').style.top=e.clientY+'px';});
document.getElementById('pullThread').onclick=()=>document.getElementById('accessPanel').classList.add('open');
document.getElementById('accessForm').onsubmit=e=>{e.preventDefault();const v=document.getElementById('codeInput').value.trim().toUpperCase();if(v===activeCode){document.getElementById('gate').style.display='none';document.body.classList.remove('locked');document.getElementById('site').classList.add('unlocked');document.getElementById('site').removeAttribute('aria-hidden');document.getElementById('siteNav').classList.add('visible');location.hash='definition';}else{document.getElementById('codeError').textContent='Wrong code. Type the generated keyword exactly.'}};
function renderMapCase(key){const c=cases[key];document.querySelectorAll('.pin').forEach(p=>p.classList.toggle('active',p.dataset.case===key));document.getElementById('lensTitle').textContent=c.title;document.getElementById('lensScore').textContent=c.score;document.getElementById('lensText').textContent=c.summary;document.getElementById('mapPanel').innerHTML=`<p class="mono-heading">Selected case</p><h3>${c.title}</h3><p>${c.summary}</p><div class="chip-row">${c.tags.map(t=>`<span class="chip">${t}</span>`).join('')}</div>`;}
document.querySelectorAll('.pin').forEach(p=>p.onclick=()=>renderMapCase(p.dataset.case));renderMapCase('pakistan');
function renderCaseTabs(){const tabs=document.getElementById('caseTabs');tabs.innerHTML=Object.entries(cases).map(([k,c])=>`<button data-case="${k}">${c.title}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>renderCaseStory(b.dataset.case));renderCaseStory('pakistan');}
function renderCaseStory(key){const c=cases[key];document.querySelectorAll('#caseTabs button').forEach(b=>b.classList.toggle('active',b.dataset.case===key));document.getElementById('caseStory').innerHTML=`<article class="story-card full"><h3>${c.title}</h3><p>${c.summary}</p></article><article class="story-card"><h3>Material conditions</h3><ul>${c.material.map(x=>`<li>${x}</li>`).join('')}</ul></article><article class="story-card"><h3>Symbolic conditions</h3><ul>${c.symbolic.map(x=>`<li>${x}</li>`).join('')}</ul></article><article class="story-card full"><h3>Diagnostic verdict</h3><p>${c.verdict}</p></article>`;}
renderCaseTabs();
document.getElementById('sourceGrid').innerHTML=sources.map(s=>`<article class="source"><b>${s[0]}</b><p>${s[1]}</p></article>`).join('');
function answerFor(q){const l=q.toLowerCase();if(l.includes('pakistan'))return answers.pakistan;if(l.includes('meta')||l.includes('tech'))return answers.meta;if(l.includes('ukraine'))return answers.ukraine;if(l.includes('definition')||l.includes('what is sovereignty'))return answers.definition;return 'Winston would first identify the organizing body, then map its claim, then separate material and symbolic conditions, then classify the domain as zero-sum, shared, or entangled. The useful answer is not “what does sovereignty say in law?” but “what conditions must this actor control or discipline to reproduce itself over time?”';}
function sendChat(q){const out=document.getElementById('chatOutput');out.insertAdjacentHTML('beforeend',`<div class="user-message"><p>${q}</p></div>`);setTimeout(()=>{out.insertAdjacentHTML('beforeend',`<div class="winston-message"><b>Winston</b><p>${answerFor(q)}</p></div>`);out.scrollTop=out.scrollHeight;},240);out.scrollTop=out.scrollHeight;}
document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>sendChat(b.dataset.prompt));document.getElementById('chatForm').onsubmit=e=>{e.preventDefault();const i=document.getElementById('chatInput');if(i.value.trim()){sendChat(i.value.trim());i.value='';}};
const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.animate([{opacity:0,transform:'translateY(24px)'},{opacity:1,transform:'translateY(0)'}],{duration:700,fill:'both',easing:'ease-out'});}),{threshold:.15});document.querySelectorAll('.section > *:not(.gate-bg):not(.access-panel)').forEach(el=>reveal.observe(el));
